package day41_Exceptions03;

public class C04_Exceptions04 {

	public static void main(String[] args) {
		
		int arr [] = {1,4,7,8};
		
		System.out.println(arr[20]);// exceptýon verir ve kodun çalýþmasýný durdurur.
		
		/*
		 !! try calýþtýgý zaman catch calýsmaz fakat finally block her durumda calýþýr 
		 */

	}

}
